#!/bin/bash

# save and run
# . install

CPUC=`cat /proc/cpuinfo | grep processor | wc -l`
CPUC=$((CPUC-1))
PARENTF=`pwd`
BUILDF="$PARENTF/build"
NGINXV='nginx-1.18.0'
IS_LOCAL=1
IS_PAUSED=0
IS_GET_ONLY=0


function main {
    notice "builder for $NGINXV"
    notice "from parent folder $PARENTF"
    
    pushd etc_src
        
        if [ $IS_GET_ONLY == 0 ]; then
            pushd 'sregex.git'
                make clean
                rm -rf build ; mkdir build
                
                if [ $IS_LOCAL == 1 ]; then
                    make -j4 PREFIX=$PARENTF/etc_src/sregex.git/build
                    make install PREFIX=$PARENTF/etc_src/sregex.git/build
                else
                    make -j4
                    make install
                fi
                ldconfig
            popd
        fi
        
        if [ $IS_GET_ONLY == 0 ]; then
            pushd 'drizzle7-2011.07.21'
                rm -rf build ; mkdir build
                
                if [ $IS_LOCAL == 1 ]; then
                    ./configure --without-server --prefix=$PARENTF/etc_src/drizzle7-2011.07.21/build
                else
                    ./configure --without-server
                fi
                
                make libdrizzle-1.0 -j4
                make install-libdrizzle-1.0 -j4
                ldconfig
            popd
        fi
        
        if [ $IS_GET_ONLY == 0 ]; then
            pushd 'modsecurity-v3.0.4'
                
                make clean
                
                if [ $IS_LOCAL == 1 ]; then
                    ./configure --prefix=$BUILDF/modsecurity
                else
                    # /usr/local/modsecurity
                    ./configure
                fi
                
                make install -j$CPUC
            popd
        fi
        
    popd
    
    
    pushd lua_src
        if [ $IS_GET_ONLY == 0 ]; then
            pushd 'luajit2.git'
                
                make clean
                mkdir build
                
                if [ $IS_LOCAL == 1 ]; then
                    make -j4 PREFIX=$PARENTF/lua_src/luajit2.git/build
                    make install PREFIX=$PARENTF/lua_src/luajit2.git/build
                else
                    make -j4 PREFIX=/opt/lua_src/luajit2.git/build
                    make install PREFIX=/opt/lua_src/luajit2.git/build
                fi
            popd
        fi
        
        if [ $IS_GET_ONLY == 0 ]; then
            local LUAJIT2_SRC=""
            if [ $IS_LOCAL == 1 ]; then
                LUAJIT2_SRC="$PARENTF/lua_src/luajit2.git/src"
            else
                LUAJIT2_SRC="/opt/lua_src/luajit2.git/src"
            fi
            
            pushd 'lua-cjson.git'
                echo
                echo "export LUA_INCLUDE_DIR=\"$LUAJIT2_SRC\" && make -j4"
                echo
                export LUA_INCLUDE_DIR="$LUAJIT2_SRC" && make -j4
                
                if [ $IS_PAUSED == 1 ]; then
                    read -p "Press [Enter] key to continue..."
                fi
            popd
        fi
        
        if [ $IS_GET_ONLY == 0 ]; then
            pushd 'lua-resty-signal.git'
                make clean
                make
            popd
        fi
        
        
        
        
    popd
    
    
    echo
    notice "save these strings:"
    if [ $IS_LOCAL == 1 ]; then
        local LB="$PARENTF/lua_src/lua-resty-core.git/lib/?.lua;"
        LB="$LB$PARENTF/lua_src/lua-resty-lrucache.git/lib/?.lua;"
        LB="$LB$PARENTF/lua_src/lua-resty-redis.git/lib/?.lua;"
        LB="$LB$PARENTF/lua_src/lua-resty-mysql.git/lib/?.lua;"
        LB="$LB$PARENTF/lua_src/lua-ssl-nginx-module.git/lualib/?.lua;"
        
        LB="$LB$PARENTF/lua_src/lua-resty-signal.git/lib/?.lua;"
        LB="$LB$PARENTF/lua_src/lua-tablepool.git/lib/?.lua;"
        LB="$LB$PARENTF/lua_src/lua-resty-shell.git/lib/?.lua;"
        
        local CLB="$PARENTF/lua_src/lua-cjson.git/?.so;"
        CLB="$CLB$PARENTF/lua_src/lua-resty-signal.git/?.so;"
        
        echo "lua_package_path \"$LB;\";"
        echo "lua_package_cpath \"$CLB;\";"
        echo "lua_package_path \"$LB;\";" > "$PARENTF/lua_package_path"
        echo "lua_package_cpath \"$CLB;\";" >> "$PARENTF/lua_package_path"
    else
        local LB="/opt/lua_src/lua-resty-core.git/lib/?.lua;"
        LB="$LB/opt/lua_src/lua-resty-lrucache.git/lib/?.lua;"
        LB="$LB/opt/lua_src/lua-resty-redis.git/lib/?.lua;"
        LB="$LB/opt/lua_src/lua-resty-mysql.git/lib/?.lua;"
        LB="$LB/opt/lua_src/lua-ssl-nginx-module.git/lualib/?.lua;"
        
        LB="$LB/opt/lua_src/lua-resty-signal.git/lib/?.lua;"
        LB="$LB/opt/lua_src/lua-tablepool.git/lib/?.lua;"
        LB="$LB/opt/lua_src/lua-resty-shell.git/lib/?.lua;"
        
        local CLB="/opt/lua_src/lua-cjson.git/?.so;"
        CLB="$CLB/opt/lua_src/lua-resty-signal.git/?.so;"
        
        echo "lua_package_path \"$LB;\";"
        echo "lua_package_cpath \"$CLB;\";"
        echo "lua_package_path \"$LB;\";" > "$PARENTF/lua_package_path"
        echo "lua_package_cpath \"$CLB;\";" >> "$PARENTF/lua_package_path"
    fi
    echo
    
    
    
    make_configure
    
    
}


# ------------------------------------------------------------------------------

function make_configure {
    
    notice "make_configure"
    
    local PREFIX=""
    local CONF_PATH=""
    local PID_PATH=""
    local ERROR_LOG=""
    local HTTP_LOG=""
    local CLIENT_BODY_TEMP=""
    local PROXY_TEMP_PATH=""
    local FASTCGI_TEMP_PATH=""
    local UWSGI_TEMP_PATH=""
    local SCGI_TEMP_PATH=""
    local LUAJIT2_BUILD_LIB=""
    local LUAJIT2_SRC=""
    local LUA_SSL_NGINX_MODULE=""
    
    if [ $IS_LOCAL == 1 ]; then
        mkdir -p $PARENTF/build/{tmp,proxy,fastcgi,uwsgi,scgi}
        PREFIX="$PARENTF/build/"
        CONF_PATH="$PREFIX/conf/nginx.conf"
        PID_PATH="$PREFIX/logs/nginx.pid"
        ERROR_LOG="$PREFIX/logs/error.log"
        HTTP_LOG="$PREFIX/logs/access.log"
        CLIENT_BODY_TEMP="$PREFIX/tmp/"
        PROXY_TEMP_PATH="$PREFIX/proxy/"
        FASTCGI_TEMP_PATH="$PREFIX/fastcgi/"
        UWSGI_TEMP_PATH="$PREFIX/uwsgi/"
        SCGI_TEMP_PATH="$PREFIX/scgi/"
        LUAJIT2_BUILD_LIB="$PARENTF/lua_src/luajit2.git/build/lib"
        LUAJIT2_SRC="$PARENTF/lua_src/luajit2.git/src"
        LUA_SSL_NGINX_MODULE="$PARENTF/lua_src/lua-ssl-nginx-module.git/"
    else
        PREFIX="/usr/local/$NGINXV"
        CONF_PATH="/etc/$NGINXV/nginx.conf"
        PID_PATH="/var/run/nginx/nginx.pid"
        ERROR_LOG="/var/log/nginx/error.log"
        HTTP_LOG="/var/log/nginx/access.log"
        CLIENT_BODY_TEMP="/var/lib/nginx/tmp/"
        PROXY_TEMP_PATH="/var/lib/nginx/proxy/"
        FASTCGI_TEMP_PATH="/var/lib/nginx/fastcgi/"
        UWSGI_TEMP_PATH="/var/lib/nginx/uwsgi/"
        SCGI_TEMP_PATH="/var/lib/nginx/scgi/"
        LUAJIT2_BUILD_LIB="/opt/lua_src/luajit2.git/build/lib"
        LUAJIT2_SRC="/opt/lua_src/luajit2.git/src"
        LUA_SSL_NGINX_MODULE="/opt/lua_src/lua-ssl-nginx-module.git/"
    fi
    
    WITH_OPENSSL=""
    if [ -d openssl-OpenSSL_1_1_1g ]; then
        WITH_OPENSSL="--with-openssl=$PARENTF/etc_src/openssl-OpenSSL_1_1_1g --with-openssl-opt='enable-tls1_3'"
    fi
    
    
cat << L10HEREDOC > ngx_src/$NGINXV/nginx_configuration
#!/bin/bash

./configure \\
--with-cc-opt="-Wno-sign-compare -Wno-string-plus-int -Wno-deprecated-declarations -Wno-unused-parameter -Wno-unused-const-variable -Wno-conditional-uninitialized -Wno-mismatched-tags -Wno-sometimes-uninitialized -Wno-parentheses-equality -Wno-tautological-compare -Wno-self-assign -Wno-deprecated-register -Wno-deprecated -Wno-invalid-source-encoding -Wno-pointer-sign -Wno-parentheses -Wno-enum-conversion -Wno-c++11-compat-deprecated-writable-strings -Wno-write-strings" \\
--with-ld-opt="-Wl,-rpath,$LUAJIT2_BUILD_LIB" \\
--prefix=$PREFIX \\
--conf-path=$CONF_PATH \\
--pid-path=$PID_PATH \\
--error-log-path=$ERROR_LOG \\
--http-log-path=$HTTP_LOG \\
--http-client-body-temp-path=$CLIENT_BODY_TEMP \\
--http-proxy-temp-path=$PROXY_TEMP_PATH \\
--http-fastcgi-temp-path=$FASTCGI_TEMP_PATH \\
--http-uwsgi-temp-path=$UWSGI_TEMP_PATH \\
--http-scgi-temp-path=$SCGI_TEMP_PATH \\
--user=nginx \\
--group=nginx \\
--with-debug \\
--with-stream \\
--with-stream_ssl_module \\
--with-stream_ssl_preread_module \\
--with-threads \\
--with-file-aio \\
--with-http_ssl_module $WITH_OPENSSL \\
--with-http_v2_module \\
--with-http_realip_module \\
--with-http_addition_module \\
--with-http_image_filter_module \\
--with-http_geoip_module \\
--with-http_sub_module \\
--with-http_mp4_module \\
--with-http_gunzip_module \\
--with-http_gzip_static_module \\
--with-http_random_index_module \\
--with-http_secure_link_module \\
--with-http_stub_status_module \\
--with-pcre \\
--with-pcre-jit \\
--with-libatomic \\
--add-module=../../ngx_module/memc-nginx-module.git/ \\
--add-module=../../ngx_module/lua-nginx-module.git/ \\
--add-module=../../ngx_module/ngx_devel_kit.git/ \\
--add-module=../../ngx_module/redis2-nginx-module.git/ \\
--add-module=../../ngx_module/echo-nginx-module.git/ \\
--add-module=../../ngx_module/form-input-nginx-module.git/ \\
--add-module=../../ngx_module/set-misc-nginx-module.git/ \\
--add-module=../../ngx_module/nginx-upload-module.git/ \\
--add-module=../../ngx_module/ngx_cache_purge.git/ \\
--add-module=../../ngx_module/headers-more-nginx-module.git/ \\
--add-module=../../ngx_module/naxsi.git/naxsi_src/ \\
--add-module=../../ngx_module/ModSecurity-nginx.git/ \\
--add-module=../../ngx_module/replace-filter-nginx-module.git/ \\
--add-module=../../ngx_module/rds-json-nginx-module.git/ \\
--add-module=../../ngx_module/rds-csv-nginx-module.git/ \\
--add-module=../../ngx_module/drizzle-nginx-module.git/ \\
--add-module=../../ngx_module/ngx_postgres.git/ \\
--add-module=../../ngx_module/njs.git/nginx/ \\
--add-module=../../ngx_module/stream-lua-nginx-module.git/ \\
--add-module=../../ngx_module/xss-nginx-module.git/ \\
--add-module=../../ngx_module/nginx-rtmp-module.git/ \\
--add-module=../../ngx_module/nginx-ts-module.git/ \\
--add-module=$LUA_SSL_NGINX_MODULE \\

L10HEREDOC
    
    chmod +x "ngx_src/$NGINXV/nginx_configuration"
    
    notice "export these environment:"
    echo "unset LUAJIT_LIB && unset LUAJIT_INC"
    echo "unset SREGEX_LIB && unset SREGEX_INC"
    echo "unset LIBDRIZZLE_INC && unset LIBDRIZZLE_LIB"
    echo "unset MODSECURITY_INC && unset MODSECURITY_LIB"
    echo
    echo "export LUAJIT_LIB=$LUAJIT2_BUILD_LIB && export LUAJIT_INC=$LUAJIT2_SRC"
    
    if [ $IS_LOCAL == 1 ]; then
        echo "export SREGEX_LIB=$PARENTF/etc_src/sregex.git/build/lib && export SREGEX_INC=$PARENTF/etc_src/sregex.git/src"
        echo "export LIBDRIZZLE_INC=$PARENTF/etc_src/drizzle7-2011.07.21/build/include/libdrizzle-1.0 && export LIBDRIZZLE_LIB=$PARENTF/etc_src/drizzle7-2011.07.21/build/lib64/"
        echo "export MODSECURITY_INC=$BUILDF/modsecurity/include/"
        echo "export MODSECURITY_LIB=$BUILDF/modsecurity/lib64/"
    fi
    echo
    
    notice 'run ./nginx_configuration'
    notice 'make install -j4'
    
    cd ngx_src/$NGINXV && exec bash
}

# ------------------------------------------------------------------------------

function notice {
    builtin echo -en "\033[1m"
    echo "NOTICE: $@"
    builtin echo -en "\033[0m"
}

function success {
    builtin echo -en "\033[1;32m"
    echo "SUCCESS: $@"
    builtin echo -en "\033[0m"
}

function warn {
    builtin echo -en "\033[1;33m"
    echo "WARN: $@"
    builtin echo -en "\033[0m"
}

function err {
    builtin echo -en "\033[1;31m"
    echo "ERR: $@"
    builtin echo -en "\033[0m"
    exit 1
}

function fatal {
    builtin echo -en "\033[1;31m"
    echo "FATAL: $@"
    builtin echo -en "\033[0m"
    exit 1
}

# ------------------------------------------------------------------------------

main
