sudo: required
dist: trusty

os: linux

language: c

compiler:
  - gcc
  - clang

install:
    - sudo apt-get update > build.log 2>&1 || (cat build.log && exit 1)
    - sudo apt-get install -qq -y cpanminus libipc-run3-perl > build.log 2>&1 || (cat build.log && exit 1)
    - sudo cpanm --notest Test::Base Test::LongString > build.log 2>&1 || (cat build.log && exit 1)

script:
  - make > build.log 2>&1 || (cat build.log && exit 1)
  - prove -r t
